###
GET http://localhost:8000/products

###
POST http://localhost:8000/products/create
Content-Type: application/json

{
    "name":"Produto 1",
    "price":10.1
}

###
POST http://localhost:8000/products/create
Content-Type: application/json

{
    "name":"Produto 2",
    "price":20.2
}

###
POST http://localhost:8000/products/877b09dd-3057-4f7a-97ed-4015bd25af5f/buy
Content-Type: application/json

{
    "amount":100
}

###
POST http://localhost:8000/products/877b09dd-3057-4f7a-97ed-4015bd25af5f/sell
Content-Type: application/json

{
    "amount":50
}